### PR TITLE
[AF-2701] add treemap

### PR DESCRIPTION
**Pull request by manaswinidas**
The props are available at https://bit.dev/recharts/recharts/treemap

### CODE REVIEW

**Comment by jesuino** [comment]
Hello Das,

Thanks for this new component - it works! We need to have a minimal working component:

* Support Data
* Make sure that we use the component pallet.

As a bonus we could:

* Support animation parameters.

**Review by jesuino — CHANGES_REQUESTED** [review]
Hello @manaswinidas 

Thanks for your changes! I noticed only one issue: when the animation is changed the component is messed, see:
treemap


Once this is fixed we are good to merge this component - thanks!

**Comment by manaswinidas** [comment]
@jesuino Thanks for pointing this out. Though this shouldn't be the case. I noticed the strange behaviour. But I guess the component is getting messed if the animationduration is less than 1500 :thinking:

**Comment by jesuino** [comment]
Looks good to me, thanks for your great work, @manaswinidas

**Pull request merged**
